### PR TITLE
Fix & complete contract ABIs, export Typechain contract types and factories

### PR DESCRIPTION
**Pull request by jfschwarz**
This PR adds the correct ABIs for all zodiac module contracts. It also sets up Typechain so the `@gnosis.pm/zodiac` will now export interfaces and factories for all our contracts. This should make this package more useful when building apps on top of our contracts.

While doing this wholesale review I couldn't resist clearing out some inconsistencies in the names of some of the existing exports:
- removed the interface formerly exported as `ContractAddresses` (which is not used anywhere afaict)
- renamed export: `SUPPORTED_NETWORKS` -> `SupportedNetworks`
- renamed export: `CONTRACT_ADDRESSES` -> `ContractAddresses`
- renamed export: `CONTRACT_ABIS` -> `ContractAbis`

All of these are **BREAKING CHANGES** meaning we must publish this as `v2.0.0`.

### CODE REVIEW

**Comment by auryn-macmillan** [comment]
> We could even setup typechain to export fully typed ethers contract factories for our contracts.

Yeah, I really like this idea.

**Comment by manboy-eth** [comment]
Sounds great. I also noticed this problem when adding new known contracts. I ended up adding the "raw" ABI here: https://github.com/gnosis/zodiac/tree/master/src/abi.
It probably makes more sense to add the full .json ABI file (like you propose) instead of the way I did it to make it easier for Typechain.

**Review by manboy-eth — CHANGES_REQUESTED** [review]
Nice work.

There is only one thing; the old `factory` file (`src/factory/factory.ts`) is added back in. The functionality that was previously in that file is now improved/updated and is in the `moduleDeployer` file (`src/factory/moduleDeployer.ts`). Perhaps we can just remove the `factory` file (`src/factory/factory.ts`) again?

**Comment by jfschwarz** [comment]
> There is only one thing; the old `factory` file (`src/factory/factory.ts`) is added back in. The functionality that was previously in that file is now improved/updated and is in the `moduleDeployer` file (`src/factory/moduleDeployer.ts`). Perhaps we can just remove the `factory` file (`src/factory/factory.ts`) again?

Ah, great catch! I've fixed it now.

**Review by manboy-eth — APPROVED** [review]
LGTM

**Pull request merged**
