### PR TITLE
Update natspec comments

### PR DESCRIPTION
**Pull request by byterose**

### CODE REVIEW

**Comment by auryn-macmillan** [comment]
Cool. I'm down for that change then. @byterose do you want to add that to this PR or should we merge it in with a separate PR?

**Comment by byterose** [comment]
@cbrzn @auryn-macmillan thank you for your input. I will add the necessary changes to this pr soon.

**Comment by byterose** [comment]
@cbrzn @auryn-macmillan finished : )

**Review by auryn-macmillan — APPROVED** [review]
lgtm!

**Pull request merged**
