### PR TITLE
Chore: Update addresses with mastercopy & remove custom singleton

### PR DESCRIPTION
**Pull request by cbrzn**
Changes proposed:
- Now we are using singleton deployment from hardhat deploy, and removed custom code
- Addresses has been updated to mastercopy

### CODE REVIEW

**Comment by auryn-macmillan** [comment]
This is looking great, @cbrzn.
Are you able to verify all of the contracts as well?

**Comment by cbrzn** [comment]
@auryn-macmillan just deployed the contracts :-D

will verify em all now in matic and xdai

**Review by carlosfebres — APPROVED** [review]
LGTM, great job! 🚀

**Comment by auryn-macmillan** [comment]
Thanks @cbrzn! Looks good to me.

**Pull request merged**
