### PR TITLE
Declare that Modifier implements IAvatar

### PR DESCRIPTION
**Pull request by jfschwarz**

### CODE REVIEW

**Review by carlosfebres — APPROVED** [review]
I think this makes total sense and also noticed this is totally valid while taking a look at the Roles Modifier.
Also, these changes don't require to audit the contract again.

**Comment by carlosfebres** [comment]
@auryn-macmillan please take a look when you're available 🚀

**Review by auryn-macmillan — APPROVED** [review]
lgtm

**Comment by auryn-macmillan** [comment]
Tests are failing after squashing some merge conflicts. I don't have time to look into it today, but happy to merge the changes once the tests are passing.

**Pull request merged**
