### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pythonpete32**
correction

### Checklist

*Prior to being merged, this PR must meet the following requirements.*

This PR:

- [x] Adds details of the module to the [README](../../README.md) (items are sorted alphabetically)

   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -

**recheck**

### CODE REVIEW

**Comment by pythonpete32** [comment]
I have read the CLA Document and I hereby sign the CLA
recheck

**Comment by pythonpete32** [comment]
recheck

**Review by auryn-macmillan — APPROVED** [review]
lgtm. Thanks for the PR!

**Comment by auryn-macmillan** [comment]
@pythonpete32 could you please post the following line as a comment to satisfy the CLA bot?

> *I have read the CLA Document and I hereby sign the CLA*

**Comment by pythonpete32** [comment]
> _I have read the CLA Document and I hereby sign the CLA_



    I have read the CLA Document and I hereby sign the CLA


as in here 😅

**Comment by auryn-macmillan** [comment]
recheck

**Pull request merged**
