### PR TITLE
Deploy replay

### PR DESCRIPTION
**Pull request by auryn-macmillan**
This PR adds a script to allow easy deployment of mastercopies to each supported network.

Run `yarn deploy-replay` to replay deployment to each of the networks defined in `hardhat.config.ts`.

Reviewers should confirm that the deployed bytecode corresponds to the audited code and that each of the new mastercopy addresses corresponds to the correct and verifiable addresses on etherscan (they have all been deployed and verified on goerli already).

### CODE REVIEW

**Comment by auryn-macmillan** [comment]
@nginnever could you please review that each of the new mastercopy addresses corresponds to the correct and verified bytecode on etherscan? I've deployed and verified them all to goerli.

**Comment by nginnever** [comment]
REALITY_ETH (0x4e35DA39Fa5893a70A40Ce964F993d891E607cC0): Deployed InitCode matches stored MasterCopyInitData sha256 hash: 2d53c15bec382e2c6bb826a111d37a610e4292f05c414fa0fb6a3e1981cbcd91

REALITY_ERC20 (0x7276813b21623d89BA8984B225d5792943DD7dbF): Deployed InitCode matches stored MasterCopyInitData sha256 hash: 86a65ba15ca421dce884198b5371b48dea14e0fd2e745d0d904a5d566d039a63

BRIDGE (0x03B5eBD2CB2e3339E93774A1Eb7c8634B8C393A9): Deployed InitCode matches stored MasterCopyInitData sha256 hash: ece45739fe2d0c954b48be56c0454d837cebeb1f6f1c2b13846809a8bf3f0b4c

DELAY (0xD62129BF40CD1694b3d9D9847367783a1A4d5cB4): Deployed InitCode matches stored MasterCopyInitData sha256 hash: 8b0ec02e713768392798a1999d2f4faeff65601801d3072d8e8551f619345267

EXIT_ERC20 (0x3ed380a282aDfA3460da28560ebEB2F6D967C9f5): Deployed InitCode matches stored MasterCopyInitData sha256 hash: 01c07318112572a76a47534fd0330e280cd6ac97b1ca8103cd374445f12de1e9

EXIT_ERC721 (0xE0eCE32Eb4BE4E9224dcec6a4FcB335c1fe05CDe): Deployed InitCode matches stored MasterCopyInitData sha256 hash: a356ff069082c2870a9113b9efe161328ee246e3fa9cedde78d1f81dc3336d7b

SCOPE_GUARD (0xeF27fcd3965a866b22Fb2d7C689De9AB7e611f1F): Deployed InitCode matches stored MasterCopyInitData sha256 hash: b3a66289c204e0cac9fd0e60a41913c3146cd1e3ad12dc5871e6220a021def07

CIRCULATING_SUPPLY_ERC20 (0x5Ed57C291a184cc244F5c9B5E9F11a8DD08BBd12): Deployed InitCode matches stored MasterCopyInitData sha256 hash: 5a96d6f05d717a82aa9f68ff729b89a02001126986f1928089881ee364b81afc

CIRCULATING_SUPPLY_ERC721 (0xBD34D00dC0ae37C687F784A11FA6a0F2c5726Ba3): Deployed InitCode matches stored MasterCopyInitData sha256 hash: c2f84027bc24d5aa26ac97e28a71230b856b0626f77b5a812a563dae13a88a90

ROLES (0xD8DfC1d938D7D163C5231688341e9635E9011889): Deployed InitCode matches stored MasterCopyInitData sha256 hash: fa6bc4f2d430df8214b40a39bc12100729b6a1e03d397d4067116cea1add4e94

OPTIMISTIC_GOVERNOR (0xe28c39FAC73cce2B33C4C003049e2F3AE43f77d5): missing initCode stored

OZ_GOVERNOR (0xe28c39FAC73cce2B33C4C003049e2F3AE43f77d5): Deployed InitCode matches stored MasterCopyInitData sha256 hash: 41dacd341b4edbd2259b5509146d8cf95502a054c93805e52bee08b4a668bec6

ERC20_VOTES (0x752c61de75ADA0F8a33e048d2F773f51172f033e): Deployed InitCode matches stored MasterCopyInitData sha256 hash: 427492de338ce1a2703ec6836cede726e56ef68dc35cf69e44ebed9dedaae33c

ERC721_VOTES (0xeFf38b2eBB95ACBA09761246045743f40e762568): Deployed InitCode matches stored MasterCopyInitData sha256 hash: 4c6e41f8b4c0ea0f9ce784cfb59913824489be6a647e6f396e9a4abf49ece5cc

MULTISEND_ENCODER (0xb67EDe523171325345780fA3016b7F5221293df0): Deployed InitCode matches stored MasterCopyInitData sha256 hash: b45abfd56823ebf74e081211db833a4c3fbec135a53fb2b3176e524b3e904d26

PERMISSIONS (0x33D1C5A5B6a7f3885c7467e829aaa21698937597): Deployed InitCode matches stored MasterCopyInitData sha256 hash: 54f73e0efdb8c9430c8f16322cf023234b5a8ed5d8cf9e0c1cce39ec14317704

CONNEXT (0x7dE07b9De0bf0FABf31A188DE1527034b2aF36dB): Deployed InitCode matches stored MasterCopyInitData sha256 hash: bcfa728f45230201e71f1b02ea255969953512d84be784efa4f01912b961a67d

On-chain deploys on goerli match all aside from missing OPTIMISTIC_GOVERNOR

**Comment by auryn-macmillan** [comment]
Thanks, @nginnever!
The other thing I need validation on is that the deployed contracts are in fact the same as the audited code in the repos.

**Comment by auryn-macmillan** [comment]
@nginnever, hit me with an approval whenever this looks good to you.

**Review by nginnever — APPROVED** [review]
Deployed bytecode from latest commits only has minimal changes from audit commit hash. Lgtm

**Pull request merged**
