### PR TITLE
fix tellor proxy init

### PR DESCRIPTION
**Pull request by QuintusTheFifth**
### Bug Report
fix Tellor module proxy initialization

### Implementation

Adds the new contract deployments to fix the proxy initialization issue.

This PR:

- [ ] Adds details of the module to the [README](../../README.md) (items are sorted alphabetically)
- [x] Adds addresses of the canonical deployments of the mastercopy for your module to [deployments.json](../../src/deployments.json), along with addresses and ABI details to [constants.ts](../../src/factory/constants.ts). Ideally these should be deterministic deployments that can be easily replicated on other supported networks.
- [ ] Includes an audit from a reputable auditor.

### CODE REVIEW

**Comment by QuintusTheFifth** [comment]
recheck

**Comment by auryn-macmillan** [comment]
Thanks for this, @QuintusTheFifth.
It seems to me that the current solution will end up being quite bloated as we add more networks.
Could we not achieve a similar result with less bloat by merging objects?
Something like this:
(honestly not sure if this works, but if feels like something like this should)
```ts
export const CONTRACT_ADDRESSES: Record<
  number,
  Record<KnownContracts, string>
> = {
  1: {
    ...MasterCopyAddresses,
    [KnownContracts.TELLOR]: "0x7D5f5EaF541AC203Ee1424895b6997041C886FBE",
  },
  4: { ...MasterCopyAddresses },
  56: { ...MasterCopyAddresses },
  100: { ...MasterCopyAddresses },
  137: { ...MasterCopyAddresses },
  31337: { ...MasterCopyAddresses },
  80001: { ...MasterCopyAddresses },
};
```

This way we don't have to define multiple copies of the same ABI and don't need a special helper script in the zodiac app.

**Comment by QuintusTheFifth** [comment]
Applied the changes

**Review by auryn-macmillan — APPROVED** [review]
lgtm

**Pull request merged**
