### PR TITLE
Update Tellor Module

### PR DESCRIPTION
**Pull request by tkernell**
### Description

The Tellor module has already been live for almost a year. This PR updates the Tellor module for better compatibility with the latest version of the Tellor oracle.

### Checklist

*Prior to being merged, this PR must meet the following requirements.*

This PR:

- [x] Adds details of the module to the [README](../../README.md) (items are sorted alphabetically) - *was already there*
- [x] Adds addresses of the canonical deployments of the mastercopy for your module to [deployments.json](../../src/deployments.json), along with addresses and ABI details to [constants.ts](../../src/factory/constants.ts). Ideally these should be deterministic deployments that can be easily replicated on other supported networks.
- [ ] Includes an audit from a reputable auditor.

### CODE REVIEW

**Comment by tkernell** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tkernell** [comment]
recheck

**Comment by tkernell** [comment]
Is there anything else we can do to improve this PR?

**Review by auryn-macmillan — APPROVED** [review]
lgtm

**Pull request merged**
