### PR TITLE
Add meta guard

### PR DESCRIPTION
**Pull request by FadhlanR**
### Title

Meta Guard

### Description

GIST: https://gist.github.com/alex-cardstack/936f05d891e8d4fb24dafd56e3179532

This PR:

- [x] Adds details of the module to the [README](../../README.md) (items are sorted alphabetically)
- [x] Adds addresses of the canonical deployments of the mastercopy for your module to [deployments.json](../../src/deployments.json), along with addresses and ABI details to [constants.ts](../../src/factory/constants.ts). Ideally these should be deterministic deployments that can be easily replicated on other supported networks.
- [ ] Includes an audit from a reputable auditor.

### CODE REVIEW

**Comment by FadhlanR** [comment]
recheck

**Comment by FadhlanR** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by FadhlanR** [comment]
recheck

**Review by auryn-macmillan — APPROVED** [review]
lgtm

**Comment by FadhlanR** [comment]
@auryn-macmillan resolved, need your re-approval.

**Review by auryn-macmillan — APPROVED** [review]

**Comment by auryn-macmillan** [comment]
Ah, it seems there are conflicts again. Sorry.

**Comment by FadhlanR** [comment]
@auryn-macmillan please help to re-approve again. Thanks.

**Review by auryn-macmillan — APPROVED** [review]

**Pull request merged**
